In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("data/yelpchi.csv")

df.head()

,review_id,user_id,product_id,review_text,rating,timestamp,label
0,0,0,0,review sample 0 with generic restaurant feedba...,3.0,2010-01-01 00:00:00,0
1,1,1,0,review sample 1 with generic restaurant feedba...,3.0,2010-01-01 01:00:00,0
2,2,2,0,review sample 2 with generic restaurant feedba...,3.0,2010-01-01 02:00:00,0
3,3,3,0,review sample 3 with generic restaurant feedba...,3.0,2010-01-01 03:00:00,0
4,4,4,0,review sample 4 with generic restaurant feedba...,3.0,2010-01-01 04:00:00,0

In [5]:
df.drop('review_id', axis=1, inplace=True)

df.head()

,user_id,product_id,review_text,rating,timestamp,label
0,0,0,review sample 0 with generic restaurant feedba...,3.0,2010-01-01 00:00:00,0
1,1,0,review sample 1 with generic restaurant feedba...,3.0,2010-01-01 01:00:00,0
2,2,0,review sample 2 with generic restaurant feedba...,3.0,2010-01-01 02:00:00,0
3,3,0,review sample 3 with generic restaurant feedba...,3.0,2010-01-01 03:00:00,0
4,4,0,review sample 4 with generic restaurant feedba...,3.0,2010-01-01 04:00:00,0

In [7]:
# df.drop('user_id', axis=1, inplace=True)
df.drop('product_id', axis=1, inplace=True)
df.drop('timestamp', axis=1, inplace=True)

In [8]:
df.head()

                                         review_text  rating  label
0  review sample 0 with generic restaurant feedba...     3.0      0
1  review sample 1 with generic restaurant feedba...     3.0      0
2  review sample 2 with generic restaurant feedba...     3.0      0
3  review sample 3 with generic restaurant feedba...     3.0      0
4  review sample 4 with generic restaurant feedba...     3.0      0

In [9]:
df.to_csv("data/yelpchi_cleaned.csv", index=False)